// Date: 10/11/2013 17:25:54
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package opticraft.client.models;

import java.util.List;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBox;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class SolarCollectorModel extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer LstrutF;
    ModelRenderer RstrutF;
    ModelRenderer LstrutT;
    ModelRenderer RstrutT;
    public ModelRenderer sPanel;
  
  public SolarCollectorModel()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 16, 1, 16);
      Base.setRotationPoint(-8F, 23F, -8F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      LstrutF = new ModelRenderer(this, 42, 23);
      LstrutF.addBox(0F, 0F, 0F, 8, 1, 1);
      LstrutF.setRotationPoint(-4F, 22F, -8F);
      LstrutF.setTextureSize(64, 32);
      LstrutF.mirror = true;
      setRotation(LstrutF, 0F, 0F, 0F);
      RstrutF = new ModelRenderer(this, 42, 23);
      RstrutF.addBox(0F, 0F, 0F, 8, 1, 1);
      RstrutF.setRotationPoint(-4F, 22F, 7F);
      RstrutF.setTextureSize(64, 32);
      RstrutF.mirror = true;
      setRotation(RstrutF, 0F, 0F, 0F);
      LstrutT = new ModelRenderer(this, 56, 17);
      LstrutT.addBox(0F, 0F, 0F, 2, 4, 1);
      LstrutT.setRotationPoint(-1F, 18F, -8F);
      LstrutT.setTextureSize(64, 32);
      LstrutT.mirror = true;
      setRotation(LstrutT, 0F, 0F, 0F);
      RstrutT = new ModelRenderer(this, 56, 17);
      RstrutT.addBox(0F, 0F, 0F, 2, 4, 1);
      RstrutT.setRotationPoint(-1F, 18F, 7F);
      RstrutT.setTextureSize(64, 32);
      RstrutT.mirror = true;
      setRotation(RstrutT, 0F, 0F, 0F);
      sPanel = new ModelRenderer(this, 0, 17);
      sPanel.addBox(0F, 0F, 0F, 14, 1, 14);
      sPanel.setRotationPoint(-7F, 18F, -7F);
      sPanel.setTextureSize(64, 32);
      sPanel.mirror = true;
      setRotation(sPanel, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    LstrutF.render(f5);
    RstrutF.render(f5);
    LstrutT.render(f5);
    RstrutT.render(f5);
    sPanel.render(f5);
  }
  
  public void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
