// Date: 07/12/2013 15:51:21
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package opticraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class CableModel extends ModelBase
{
  //fields
    ModelRenderer BaC;
    ModelRenderer BaB;
    ModelRenderer BaL;
    ModelRenderer BaF;
    ModelRenderer BaR;
    ModelRenderer TC;
    ModelRenderer TL;
    ModelRenderer TR;
    ModelRenderer TF;
    ModelRenderer TB;
    ModelRenderer BoC;
    ModelRenderer BoB;
    ModelRenderer BoT;
    ModelRenderer BoL;
    ModelRenderer BoR;
    ModelRenderer FC;
    ModelRenderer FT;
    ModelRenderer FB;
    ModelRenderer FR;
    ModelRenderer FL;
    ModelRenderer LC;
    ModelRenderer LT;
    ModelRenderer LB;
    ModelRenderer LBa;
    ModelRenderer LF;
    ModelRenderer RC;
    ModelRenderer RT;
    ModelRenderer RB;
    ModelRenderer RBa;
    ModelRenderer RF;
  
  public CableModel()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      BaC = new ModelRenderer(this, 11, 0);
      BaC.addBox(0F, 0F, 0F, 2, 1, 2);
      BaC.setRotationPoint(-1F, 23F, -1F);
      BaC.setTextureSize(32, 32);
      BaC.mirror = true;
      setRotation(BaC, 0F, 0F, 0F);
      BaB = new ModelRenderer(this, 0, 0);
      BaB.addBox(0F, 0F, 0F, 2, 1, 7);
      BaB.setRotationPoint(-1F, 8F, 1F);
      BaB.setTextureSize(32, 32);
      BaB.mirror = true;
      setRotation(BaB, 0F, 0F, 0F);
      BaL = new ModelRenderer(this, 0, 0);
      BaL.addBox(0F, 0F, 0F, 2, 1, 7);
      BaL.setRotationPoint(1F, 23F, 1F);
      BaL.setTextureSize(32, 32);
      BaL.mirror = true;
      setRotation(BaL, 0F, 1.570796F, 0F);
      BaF = new ModelRenderer(this, 0, 0);
      BaF.addBox(0F, 0F, 0F, 2, 1, 7);
      BaF.setRotationPoint(-1F, 23F, -8F);
      BaF.setTextureSize(32, 32);
      BaF.mirror = true;
      setRotation(BaF, 0F, 0F, 0F);
      BaR = new ModelRenderer(this, 0, 0);
      BaR.addBox(0F, 0F, 0F, 2, 1, 7);
      BaR.setRotationPoint(-8F, 23F, 1F);
      BaR.setTextureSize(32, 32);
      BaR.mirror = true;
      setRotation(BaR, 0F, 1.570796F, 0F);
      TC = new ModelRenderer(this, 11, 0);
      TC.addBox(0F, 0F, 0F, 2, 1, 2);
      TC.setRotationPoint(-1F, 8F, -1F);
      TC.setTextureSize(32, 32);
      TC.mirror = true;
      setRotation(TC, 0F, 0F, 0F);
      TL = new ModelRenderer(this, 0, 0);
      TL.addBox(0F, 0F, 0F, 2, 1, 7);
      TL.setRotationPoint(1F, 8F, 1F);
      TL.setTextureSize(32, 32);
      TL.mirror = true;
      setRotation(TL, 0F, 1.570796F, 0F);
      TR = new ModelRenderer(this, 0, 0);
      TR.addBox(0F, 0F, 0F, 2, 1, 7);
      TR.setRotationPoint(-8F, 8F, 1F);
      TR.setTextureSize(32, 32);
      TR.mirror = true;
      setRotation(TR, 0F, 1.570796F, 0F);
      TF = new ModelRenderer(this, 0, 0);
      TF.addBox(0F, 0F, 0F, 2, 1, 7);
      TF.setRotationPoint(-1F, 8F, -8F);
      TF.setTextureSize(32, 32);
      TF.mirror = true;
      setRotation(TF, 0F, 0F, 0F);
      TB = new ModelRenderer(this, 0, 0);
      TB.addBox(0F, 0F, 0F, 2, 1, 7);
      TB.setRotationPoint(-1F, 23F, 1F);
      TB.setTextureSize(32, 32);
      TB.mirror = true;
      setRotation(TB, 0F, 0F, 0F);
      BoC = new ModelRenderer(this, 11, 3);
      BoC.addBox(0F, 0F, 0F, 2, 2, 1);
      BoC.setRotationPoint(-1F, 17F, 7F);
      BoC.setTextureSize(32, 32);
      BoC.mirror = true;
      setRotation(BoC, 0F, 0F, -1.570796F);
      BoB = new ModelRenderer(this, 19, 0);
      BoB.addBox(0F, 0F, 0F, 2, 7, 1);
      BoB.setRotationPoint(-1F, 17F, 7F);
      BoB.setTextureSize(32, 32);
      BoB.mirror = true;
      setRotation(BoB, 0F, 0F, 0F);
      BoT = new ModelRenderer(this, 19, 0);
      BoT.addBox(0F, 0F, 0F, 2, 7, 1);
      BoT.setRotationPoint(-1F, 8F, 7F);
      BoT.setTextureSize(32, 32);
      BoT.mirror = true;
      setRotation(BoT, 0F, 0F, 0F);
      BoL = new ModelRenderer(this, 19, 0);
      BoL.addBox(0F, 0F, 0F, 2, 7, 1);
      BoL.setRotationPoint(1F, 17F, 7F);
      BoL.setTextureSize(32, 32);
      BoL.mirror = true;
      setRotation(BoL, 0F, 0F, -1.570796F);
      BoR = new ModelRenderer(this, 19, 0);
      BoR.addBox(0F, 0F, 0F, 2, 7, 1);
      BoR.setRotationPoint(-8F, 17F, 7F);
      BoR.setTextureSize(32, 32);
      BoR.mirror = true;
      setRotation(BoR, 0F, 0F, -1.570796F);
      FC = new ModelRenderer(this, 11, 3);
      FC.addBox(0F, 0F, 0F, 2, 2, 1);
      FC.setRotationPoint(-1F, 17F, -8F);
      FC.setTextureSize(32, 32);
      FC.mirror = true;
      setRotation(FC, 0F, 0F, -1.570796F);
      FT = new ModelRenderer(this, 19, 0);
      FT.addBox(0F, 0F, 0F, 2, 7, 1);
      FT.setRotationPoint(-1F, 8F, -8F);
      FT.setTextureSize(32, 32);
      FT.mirror = true;
      setRotation(FT, 0F, 0F, 0F);
      FB = new ModelRenderer(this, 19, 0);
      FB.addBox(0F, 0F, 0F, 2, 7, 1);
      FB.setRotationPoint(-1F, 17F, -8F);
      FB.setTextureSize(32, 32);
      FB.mirror = true;
      setRotation(FB, 0F, 0F, 0F);
      FR = new ModelRenderer(this, 19, 0);
      FR.addBox(0F, 0F, 0F, 2, 7, 1);
      FR.setRotationPoint(-8F, 17F, -8F);
      FR.setTextureSize(32, 32);
      FR.mirror = true;
      setRotation(FR, 0F, 0F, -1.570796F);
      FL = new ModelRenderer(this, 19, 0);
      FL.addBox(0F, 0F, 0F, 2, 7, 1);
      FL.setRotationPoint(1F, 17F, -8F);
      FL.setTextureSize(32, 32);
      FL.mirror = true;
      setRotation(FL, 0F, 0F, -1.570796F);
      LC = new ModelRenderer(this, 0, 0);
      LC.addBox(0F, 0F, 0F, 1, 2, 2);
      LC.setRotationPoint(7F, 15F, -1F);
      LC.setTextureSize(32, 32);
      LC.mirror = true;
      setRotation(LC, 0F, 0F, 0F);
      LT = new ModelRenderer(this, 25, 0);
      LT.addBox(0F, 0F, 0F, 1, 7, 2);
      LT.setRotationPoint(7F, 8F, -1F);
      LT.setTextureSize(32, 32);
      LT.mirror = true;
      setRotation(LT, 0F, 0F, 0F);
      LB = new ModelRenderer(this, 25, 0);
      LB.addBox(0F, 0F, 0F, 1, 7, 2);
      LB.setRotationPoint(7F, 17F, -1F);
      LB.setTextureSize(32, 32);
      LB.mirror = true;
      setRotation(LB, 0F, 0F, 0F);
      LBa = new ModelRenderer(this, 25, 0);
      LBa.addBox(0F, 0F, 0F, 1, 7, 2);
      LBa.setRotationPoint(7F, 17F, 1F);
      LBa.setTextureSize(32, 32);
      LBa.mirror = true;
      setRotation(LBa, 1.570796F, 0F, 0F);
      LF = new ModelRenderer(this, 25, 0);
      LF.addBox(0F, 0F, 0F, 1, 7, 2);
      LF.setRotationPoint(7F, 17F, -8F);
      LF.setTextureSize(32, 32);
      LF.mirror = true;
      setRotation(LF, 1.570796F, 0F, 0F);
      RC = new ModelRenderer(this, 0, 0);
      RC.addBox(0F, 0F, 0F, 1, 2, 2);
      RC.setRotationPoint(-8F, 15F, -1F);
      RC.setTextureSize(32, 32);
      RC.mirror = true;
      setRotation(RC, 0F, 0F, 0F);
      RT = new ModelRenderer(this, 25, 0);
      RT.addBox(0F, 0F, 0F, 1, 7, 2);
      RT.setRotationPoint(-8F, 8F, -1F);
      RT.setTextureSize(32, 32);
      RT.mirror = true;
      setRotation(RT, 0F, 0F, 0F);
      RB = new ModelRenderer(this, 25, 0);
      RB.addBox(0F, 0F, 0F, 1, 7, 2);
      RB.setRotationPoint(-8F, 17F, -1F);
      RB.setTextureSize(32, 32);
      RB.mirror = true;
      setRotation(RB, 0F, 0F, 0F);
      RBa = new ModelRenderer(this, 25, 0);
      RBa.addBox(0F, 0F, 0F, 1, 7, 2);
      RBa.setRotationPoint(-8F, 17F, 1F);
      RBa.setTextureSize(32, 32);
      RBa.mirror = true;
      setRotation(RBa, 1.570796F, 0F, 0F);
      RF = new ModelRenderer(this, 25, 0);
      RF.addBox(0F, 0F, 0F, 1, 7, 2);
      RF.setRotationPoint(-8F, 17F, -8F);
      RF.setTextureSize(32, 32);
      RF.mirror = true;
      setRotation(RF, 1.570796F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    BaC.render(f5);
    BaB.render(f5);
    BaL.render(f5);
    BaF.render(f5);
    BaR.render(f5);
    TC.render(f5);
    TL.render(f5);
    TR.render(f5);
    TF.render(f5);
    TB.render(f5);
    BoC.render(f5);
    BoB.render(f5);
    BoT.render(f5);
    BoL.render(f5);
    BoR.render(f5);
    FC.render(f5);
    FT.render(f5);
    FB.render(f5);
    FR.render(f5);
    FL.render(f5);
    LC.render(f5);
    LT.render(f5);
    LB.render(f5);
    LBa.render(f5);
    LF.render(f5);
    RC.render(f5);
    RT.render(f5);
    RB.render(f5);
    RBa.render(f5);
    RF.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
