// Date: 05/12/2013 20:45:32
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package opticraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class LaserRedstoneModel extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer LaserMain;
    ModelRenderer StrutFrontRight;
    ModelRenderer StrutFrontLeft;
    ModelRenderer StrutBack;
    ModelRenderer PoleFrontRight;
    ModelRenderer PoleFrontLeft;
    ModelRenderer Clamp;
    ModelRenderer FrontLaser;
    ModelRenderer Top;
  
  public LaserRedstoneModel()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 0, 13);
      Base.addBox(0F, 0F, 0F, 6, 1, 6);
      Base.setRotationPoint(-3F, 23.5F, 2F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      LaserMain = new ModelRenderer(this, 0, 20);
      LaserMain.addBox(0F, 0F, 0F, 2, 2, 8);
      LaserMain.setRotationPoint(-1F, 15F, -7F);
      LaserMain.setTextureSize(64, 32);
      LaserMain.mirror = true;
      setRotation(LaserMain, 0F, 0F, 0F);
      StrutFrontRight = new ModelRenderer(this, 0, 0);
      StrutFrontRight.addBox(0F, 0F, 0F, 1, 1, 12);
      StrutFrontRight.setRotationPoint(-2F, 16F, -6F);
      StrutFrontRight.setTextureSize(64, 32);
      StrutFrontRight.mirror = true;
      setRotation(StrutFrontRight, -0.6981317F, 0F, 0F);
      StrutFrontLeft = new ModelRenderer(this, 0, 0);
      StrutFrontLeft.addBox(0F, 0F, 0F, 1, 1, 12);
      StrutFrontLeft.setRotationPoint(1F, 16F, -6F);
      StrutFrontLeft.setTextureSize(64, 32);
      StrutFrontLeft.mirror = true;
      setRotation(StrutFrontLeft, -0.6981317F, 0F, 0F);
      StrutBack = new ModelRenderer(this, 26, 0);
      StrutBack.addBox(0F, 0F, 0F, 1, 1, 12);
      StrutBack.setRotationPoint(-0.5F, 16F, -2F);
      StrutBack.setTextureSize(64, 32);
      StrutBack.mirror = true;
      setRotation(StrutBack, -0.6981317F, 0F, 0F);
      PoleFrontRight = new ModelRenderer(this, 24, 13);
      PoleFrontRight.addBox(0F, 0F, 0F, 1, 1, 6);
      PoleFrontRight.setRotationPoint(-2F, 24F, -6F);
      PoleFrontRight.setTextureSize(64, 32);
      PoleFrontRight.mirror = true;
      setRotation(PoleFrontRight, 0.6981317F, 0F, 0F);
      PoleFrontLeft = new ModelRenderer(this, 20, 20);
      PoleFrontLeft.addBox(0F, 0F, 0F, 1, 1, 6);
      PoleFrontLeft.setRotationPoint(1F, 24F, -6F);
      PoleFrontLeft.setTextureSize(64, 32);
      PoleFrontLeft.mirror = true;
      setRotation(PoleFrontLeft, 0.6981317F, 0F, 0F);
      Clamp = new ModelRenderer(this, 20, 27);
      Clamp.addBox(0F, 0F, 0F, 4, 1, 3);
      Clamp.setRotationPoint(-2F, 16.7F, -6.6F);
      Clamp.setTextureSize(64, 32);
      Clamp.mirror = true;
      setRotation(Clamp, 0.8726646F, 0F, 0F);
      FrontLaser = new ModelRenderer(this, 0, 30);
      FrontLaser.addBox(0F, 0F, 0F, 1, 1, 1);
      FrontLaser.setRotationPoint(-0.5F, 15.5F, -8F);
      FrontLaser.setTextureSize(64, 32);
      FrontLaser.mirror = true;
      setRotation(FrontLaser, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 38, 13);
      Top.addBox(0F, 0F, 0F, 1, 1, 5);
      Top.setRotationPoint(-0.5F, 14.7F, -4.5F);
      Top.setTextureSize(64, 32);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    LaserMain.render(f5);
    StrutFrontRight.render(f5);
    StrutFrontLeft.render(f5);
    StrutBack.render(f5);
    PoleFrontRight.render(f5);
    PoleFrontLeft.render(f5);
    Clamp.render(f5);
    FrontLaser.render(f5);
    Top.render(f5);
  }
  
  public void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
