// Date: 22/11/2013 20:41:38
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package opticraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class LaserWrenchModel extends ModelBase
{
  //fields
    ModelRenderer Handle;
    ModelRenderer LeftJoin;
    ModelRenderer LeftBlock;
    ModelRenderer RightJoin;
    ModelRenderer RightBlock;
    ModelRenderer RightJoin2;
    ModelRenderer RighBlock2;
    ModelRenderer RightJoin3;
    ModelRenderer RightBlock3;
    ModelRenderer NobBack;
    ModelRenderer NobFront;
    ModelRenderer HandleDetailRight;
    ModelRenderer HandleDetailLeft;
  
  public LaserWrenchModel()
  {
    textureWidth = 34;
    textureHeight = 32;
    
      Handle = new ModelRenderer(this, 0, 0);
      Handle.addBox(0F, 0F, 0F, 2, 20, 3);
      Handle.setRotationPoint(-0.5F, 9F, -1F);
      Handle.setTextureSize(34, 32);
      Handle.mirror = true;
      setRotation(Handle, 0F, 0F, 0F);
      LeftJoin = new ModelRenderer(this, 18, 0);
      LeftJoin.addBox(0F, 0F, 0F, 1, 1, 3);
      LeftJoin.setRotationPoint(0F, 10F, 1.466667F);
      LeftJoin.setTextureSize(34, 32);
      LeftJoin.mirror = true;
      setRotation(LeftJoin, 0.5235988F, 0F, 0F);
      LeftBlock = new ModelRenderer(this, 10, 17);
      LeftBlock.addBox(0F, 0F, 0F, 2, 4, 2);
      LeftBlock.setRotationPoint(-0.5F, 5.466667F, 4.666667F);
      LeftBlock.setTextureSize(34, 32);
      LeftBlock.mirror = true;
      setRotation(LeftBlock, -0.5235988F, 0F, 0F);
      RightJoin = new ModelRenderer(this, 18, 4);
      RightJoin.addBox(0F, 0F, 0F, 1, 1, 3);
      RightJoin.setRotationPoint(0F, 8.4F, -2.933333F);
      RightJoin.setTextureSize(34, 32);
      RightJoin.mirror = true;
      setRotation(RightJoin, -0.5235988F, 0F, 0F);
      RightBlock = new ModelRenderer(this, 18, 17);
      RightBlock.addBox(0F, 0F, 0F, 2, 4, 2);
      RightBlock.setRotationPoint(-0.5F, 6.666667F, -5.066667F);
      RightBlock.setTextureSize(34, 32);
      RightBlock.mirror = true;
      setRotation(RightBlock, 0.5235988F, 0F, 0F);
      RightJoin2 = new ModelRenderer(this, 18, 8);
      RightJoin2.addBox(0F, 0F, 0F, 1, 3, 1);
      RightJoin2.setRotationPoint(0F, 3.666667F, -5.1F);
      RightJoin2.setTextureSize(34, 32);
      RightJoin2.mirror = true;
      setRotation(RightJoin2, 0.1745329F, 0F, 0F);
      RighBlock2 = new ModelRenderer(this, 26, 6);
      RighBlock2.addBox(0F, 0F, 0F, 2, 4, 2);
      RighBlock2.setRotationPoint(-0.5F, 0.4F, -3.933333F);
      RighBlock2.setTextureSize(34, 32);
      RighBlock2.mirror = true;
      setRotation(RighBlock2, -0.3490659F, 0F, 0F);
      RightJoin3 = new ModelRenderer(this, 22, 8);
      RightJoin3.addBox(0F, 0F, 0F, 1, 3, 1);
      RightJoin3.setRotationPoint(0F, -1.333333F, -1.166667F);
      RightJoin3.setTextureSize(34, 32);
      RightJoin3.mirror = true;
      setRotation(RightJoin3, -0.8726646F, 0F, 0F);
      RightBlock3 = new ModelRenderer(this, 26, 0);
      RightBlock3.addBox(0F, 0F, 0F, 2, 4, 2);
      RightBlock3.setRotationPoint(-0.5F, -2.333333F, 1.533333F);
      RightBlock3.setTextureSize(34, 32);
      RightBlock3.mirror = true;
      setRotation(RightBlock3, -1.22173F, 0F, 0F);
      NobBack = new ModelRenderer(this, 24, 12);
      NobBack.addBox(0F, 0F, 0F, 1, 2, 2);
      NobBack.setRotationPoint(1F, 9.5F, -0.5F);
      NobBack.setTextureSize(34, 32);
      NobBack.mirror = true;
      setRotation(NobBack, 0F, 0F, 0F);
      NobFront = new ModelRenderer(this, 18, 12);
      NobFront.addBox(0F, 0F, 0F, 1, 2, 2);
      NobFront.setRotationPoint(-1F, 9.5F, -0.5F);
      NobFront.setTextureSize(34, 32);
      NobFront.mirror = true;
      setRotation(NobFront, 0F, 0F, 0F);
      HandleDetailRight = new ModelRenderer(this, 10, 0);
      HandleDetailRight.addBox(0F, 0F, 0F, 1, 16, 1);
      HandleDetailRight.setRotationPoint(0F, 13F, -1.5F);
      HandleDetailRight.setTextureSize(34, 32);
      HandleDetailRight.mirror = true;
      setRotation(HandleDetailRight, 0F, 0F, 0F);
      HandleDetailLeft = new ModelRenderer(this, 14, 0);
      HandleDetailLeft.addBox(0F, 0F, 0F, 1, 16, 1);
      HandleDetailLeft.setRotationPoint(0F, 13F, 1.5F);
      HandleDetailLeft.setTextureSize(34, 32);
      HandleDetailLeft.mirror = true;
      setRotation(HandleDetailLeft, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Handle.render(f5);
    LeftJoin.render(f5);
    LeftBlock.render(f5);
    RightJoin.render(f5);
    RightBlock.render(f5);
    RightJoin2.render(f5);
    RighBlock2.render(f5);
    RightJoin3.render(f5);
    RightBlock3.render(f5);
    NobBack.render(f5);
    NobFront.render(f5);
    HandleDetailRight.render(f5);
    HandleDetailLeft.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
