// Date: 19/11/2013 15:12:01
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package opticraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class LaserDetectorModel extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Base2;
    ModelRenderer LeftL;
    ModelRenderer RightL;
    ModelRenderer Back;
    ModelRenderer Front;
    ModelRenderer Light1;
    ModelRenderer Light2;
    ModelRenderer Light3;
    ModelRenderer Light4;
  
  public LaserDetectorModel()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 14, 1, 14);
      Base.setRotationPoint(-7F, 23F, -7F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Base2 = new ModelRenderer(this, 0, 15);
      Base2.addBox(0F, 0F, 0F, 8, 1, 8);
      Base2.setRotationPoint(-4F, 22F, -4F);
      Base2.setTextureSize(64, 32);
      Base2.mirror = true;
      setRotation(Base2, 0F, 0F, 0F);
      LeftL = new ModelRenderer(this, 0, 24);
      LeftL.addBox(0F, 0F, 0F, 1, 1, 4);
      LeftL.setRotationPoint(-2F, 21F, -2F);
      LeftL.setTextureSize(64, 32);
      LeftL.mirror = true;
      setRotation(LeftL, 0F, 0F, 0F);
      RightL = new ModelRenderer(this, 10, 24);
      RightL.addBox(0F, 0F, 0F, 1, 1, 4);
      RightL.setRotationPoint(1F, 21F, -2F);
      RightL.setTextureSize(64, 32);
      RightL.mirror = true;
      setRotation(RightL, 0F, 0F, 0F);
      Back = new ModelRenderer(this, 20, 24);
      Back.addBox(0F, 0F, 0F, 2, 1, 1);
      Back.setRotationPoint(-1F, 21F, 1F);
      Back.setTextureSize(64, 32);
      Back.mirror = true;
      setRotation(Back, 0F, 0F, 0F);
      Front = new ModelRenderer(this, 20, 26);
      Front.addBox(0F, 0F, 0F, 2, 1, 1);
      Front.setRotationPoint(-1F, 21F, -2F);
      Front.setTextureSize(64, 32);
      Front.mirror = true;
      setRotation(Front, 0F, 0F, 0F);
      Light1 = new ModelRenderer(this, 0, 29);
      Light1.addBox(0F, 0F, 0F, 1, 1, 1);
      Light1.setRotationPoint(5F, 22.5F, -6F);
      Light1.setTextureSize(64, 32);
      Light1.mirror = true;
      setRotation(Light1, 0F, 0F, 0F);
      Light2 = new ModelRenderer(this, 0, 29);
      Light2.addBox(0F, 0F, 0F, 1, 1, 1);
      Light2.setRotationPoint(5F, 22.5F, 5F);
      Light2.setTextureSize(64, 32);
      Light2.mirror = true;
      setRotation(Light2, 0F, 0F, 0F);
      Light3 = new ModelRenderer(this, 0, 29);
      Light3.addBox(0F, 0F, 0F, 1, 1, 1);
      Light3.setRotationPoint(-6F, 22.5F, 5F);
      Light3.setTextureSize(64, 32);
      Light3.mirror = true;
      setRotation(Light3, 0F, 0F, 0F);
      Light4 = new ModelRenderer(this, 0, 29);
      Light4.addBox(0F, 0F, 0F, 1, 1, 1);
      Light4.setRotationPoint(-6F, 22.5F, -6F);
      Light4.setTextureSize(64, 32);
      Light4.mirror = true;
      setRotation(Light4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    Base2.render(f5);
    LeftL.render(f5);
    RightL.render(f5);
    Back.render(f5);
    Front.render(f5);
    Light1.render(f5);
    Light2.render(f5);
    Light3.render(f5);
    Light4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
